<?
$PERM["sellers_account"]["2"]="X";
$PERM["sellers_account"]["3"]="D";
$PERM["sellers_account"]["4"]="D";
$PERM["sellers_account"]["6"]="D";
$PERM["sellers_account"]["7"]="R";
$PERM["sellers_account"]["5"]="D";
$PERM["buyers-account"]["2"]="X";
$PERM["buyers-account"]["3"]="D";
$PERM["buyers-account"]["4"]="D";
$PERM["buyers-account"]["6"]="R";
$PERM["buyers-account"]["7"]="D";
$PERM["buyers-account"]["5"]="D";
$PERM["about"]["8"]="W";
$PERM["services"]["8"]="W";
$PERM["services"]["5"]="W";
$PERM["announcements"]["8"]="W";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>